# Generated by Django 4.2.7 on 2023-12-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
